# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d9aac5a0caa242753b56447d2a55ce8953cf413c3dd7e792c26df6719b9604d302b831b034d4b74a9d305643988067c0d255d29ee543adfc4fc5907156337b85

test:
  secret_key_base: 745a032fbdf4a6a1ab22a06b4750fdc95ef1b52a83673a015e56431b068e38e0069dc6ba0dbbfcadb860baedce2492a653e95d3023a824e57aac4fc7cb0d0ff3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
